config/routes.rb
Rails.application.routes.draw do

  resources :pages, only: [:new, :show, :edit, :index]
  resources :widgets
  resources :texts
  resources :headers

  get '/home' => 'pages#home'
  get '/:title' => 'pages#show'

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  has_and_belongs_to_many :pages
  belongs_to :element, polymorphic: true
  has_many :widget_attrs
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { }
        # format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.fetch(:widget, {})
      params.require(:widget).permit(:position)
    end
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.number_field :position %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/_showwidget.html.erb
<div class="actions">
  <%= link_to 'Show', widget %>
  <%= link_to 'Edit', edit_widget_path(widget) %>
  <%= link_to 'X', widget, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/widgets/create.js.erb
$('#new_widget').remove()
// $('#add_text').show()
$('#sortable_widgets').append( '<%= j render( "widgets/showwidget", widget: @widget ) %>' )

app/views/widgets/edit.html.erb
<h1>Editing Widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Widgets</h1>

<div class="sortable_elements" id="sortable_widgets">

  <% @widgets.each do |widget| %>

      <%= render( "widgets/showwidget", widget: widget ) %>

  <% end %>

</div>

<div class="add_text">
  <div class="round5 grlinks" id="add_widget" data-widget="<%= @widget %>">

    <p><%= link_to '+', new_widget_path, remote: true, class: "round5" %></p>

  </div>
</div>


<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New Widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/new.js.erb
$(function () {
  $('#add_widget').before( '<%= j render( "widgets/form", widget: @widget ) %>' )
  // $('#add_text').hide()
  // $('#newtext input').val( $('#add_text').data('text') );
});

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>