config/routes.rb
Rails.application.routes.draw do

  resources :pages, only: [:new, :show, :edit, :index]
  resources :widgets
  resources :texts
  resources :headers

  get '/home' => 'pages#home'
  get '/:title' => 'pages#show'

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w500 center inline_block">

    <div class="field">
      <%= f.label "title" %><br>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label "meta-title" %><br>
      <%= f.text_field :m_title %>
    </div>

    <div class="field">
      <%= f.label "meta-description" %><br>
      <%= f.text_area :m_desc %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/pages/_newtextform.html.erb
<div class="row">
  <div class="w500 center inline_block">
    <%= form_for text, remote: true do |f| %>
      <% if text.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(text.errors.count, "error") %> prohibited this text from being saved:</h2>

        <ul>
          <% text.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="field">
        <%= f.label "content" %>
      </div>
      <div class="field">
        <%= f.text_area :content %>
      </div>

      <div class="actions">
        <%= f.submit %>

        <%= button_to "Create", { controller: "texts", action: "create", method: :post, page: @page }, remote: true %>

        <%= link_to 'Create with button_to',
        remote: true,
        :controller => "texts",
        :action => "create",
        :method => :post,
        page: params[:page] %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/_showtext.html.erb
<p><%= truncate text.content, length: 50 %></p>
<div class="actions">
  <%= link_to 'Show', text %>
  <%= link_to 'Edit', edit_text_path(text) %>
  <%= link_to 'X', text, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/pages/edit.html.erb
<div class="container center admin">
  <div class="row">
    <h1>Editing <%= @page.title %> Page</h1>
  </div>

  <div id="add_widget" class="add_widget "></div>

  <% if !@page.widgets.blank? %>
    <div class="row">
      <div class="widgets">
        <% @page.widgets.each do |widget| %>
        <%= render widget.element, element: widget.element %>
        <%= render "widgets/showwidget", widget: widget %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="page_properties hidden">
    <%= render 'form' %>
  </div>


  <div class="left_nav">
    <div class="left_nav_toggle"></div>

    <div class="left_bar left">
      <ul>
        <li><%= link_to '+text', new_text_path(:page => @page), remote: true, class: "round5" %></li>
      </ul>

    </div>

    <% if !@page.widgets.blank? %>
      <div class="left_widget_map left">
        <% @page.widgets.each do |widget| %>
          <div class="widget_map_block block center round3"></div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pages</h1>

<% @pages.each do |page| %>
  <div class="title">
    <%= page.title %>
  </div>

  <div class="actions">
    <p>
      <%= link_to 'Show', page %>
      <%= link_to 'Edit', edit_page_path(page) %>
      <%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
<% end %>




<%= link_to 'New Page', new_page_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pages</h1>

<% @pages.each do |page| %>
  <div class="title">
    <%= page.title %>
  </div>

  <div class="actions">
    <p>
      <%= link_to 'Show', page %>
      <%= link_to 'Edit', edit_page_path(page) %>
      <%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
<% end %>




<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container center"></div>

  <div class="pagetitle">
    <%= @page.title %>
  </div>

  <% if !@widgets.blank? %>
    <% @widgets.each do |widget| %>
      <%= render widget.element, element: widget.element %>
    <% end %>
  <% end %>

  <%= link_to 'Edit', edit_page_path(@page) %> |
  <%= link_to 'Back', pages_path %>
</div>