config/routes.rb
Rails.application.routes.draw do

  resources :pages, only: [:new, :show, :edit, :index]
  resources :widgets
  resources :texts
  resources :headers

  get '/home' => 'pages#home'
  get '/:title' => 'pages#show'

end

app/models/header.rb
class Header < ActiveRecord::Base
  has_one :widget, as: :element
end

app/controllers/headers_controller.rb
class HeadersController < ApplicationController
  before_action :set_header, only: [:show, :edit, :update, :destroy]

  # GET /headers
  # GET /headers.json
  def index
    @headers = Header.all
  end

  # GET /headers/1
  # GET /headers/1.json
  def show
  end

  # GET /headers/new
  def new
    @header = Header.new
  end

  # GET /headers/1/edit
  def edit
  end

  # POST /headers
  # POST /headers.json
  def create
    @header = Header.new(header_params)

    respond_to do |format|
      if @header.save
        format.html { redirect_to @header, notice: 'Header was successfully created.' }
        format.json { render :show, status: :created, location: @header }
      else
        format.html { render :new }
        format.json { render json: @header.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /headers/1
  # PATCH/PUT /headers/1.json
  def update
    respond_to do |format|
      if @header.update(header_params)
        format.html { redirect_to @header, notice: 'Header was successfully updated.' }
        format.json { render :show, status: :ok, location: @header }
      else
        format.html { render :edit }
        format.json { render json: @header.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /headers/1
  # DELETE /headers/1.json
  def destroy
    @header.destroy
    respond_to do |format|
      format.html { redirect_to headers_url, notice: 'Header was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_header
      @header = Header.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def header_params
      params.fetch(:header, {})
      params.require(:header).permit(:content)
    end
end

app/helpers/headers_helper.rb
module HeadersHelper
end

app/views/headers/_form.html.erb
<%= form_for(@header) do |f| %>
  <% if @header.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@header.errors.count, "error") %> prohibited this header from being saved:</h2>

      <ul>
      <% @header.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "content" %>
  </div>
  <div class="field">
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/headers/_header.html.erb
<div class="header center">
  <%= element.content %>
</div>

app/views/headers/edit.html.erb
<h1>Editing Header</h1>

<%= render 'form' %>

<%= link_to 'Show', @header %> |
<%= link_to 'Back', headers_path %>

app/views/headers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Headers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @headers.each do |header| %>
      <tr>
        <td><%= link_to 'Show', header %></td>
        <td><%= link_to 'Edit', edit_header_path(header) %></td>
        <td><%= link_to 'Destroy', header, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Header', new_header_path %>

app/views/headers/new.html.erb
<h1>New Header</h1>

<%= render 'form' %>

<%= link_to 'Back', headers_path %>

app/views/headers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_header_path(@header) %> |
<%= link_to 'Back', headers_path %>