config/routes.rb
Rails.application.routes.draw do

  resources :pages, only: [:new, :show, :edit, :index]
  resources :widgets
  resources :texts
  resources :headers

  get '/home' => 'pages#home'
  get '/:title' => 'pages#show'

end

app/models/text.rb
class Text < ActiveRecord::Base
  has_one :widget, as: :element
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]

  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = Text.new
    @page = Page.find( params[:page] )
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)
    @page = Page.find( params[:page] )
    respond_to do |format|
      if @text.save
        @page.widgets.create!( element: @text )
        # format.html { render :nothing => true }
        # format.json { render :show, status: :created, location: @text }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.fetch(:text, {})
      params.require(:text).permit(:content, :id)
    end
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/texts/_form.html.erb
<div class="row">
  <div class="w500 center inline_block">
    <%= form_for text, remote: true do |f| %>
      <% if text.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(text.errors.count, "error") %> prohibited this text from being saved:</h2>

        <ul>
          <% text.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="field">
        <%= f.label "content" %>
      </div>
      <div class="field">
        <%= f.text_area :content %>
      </div>

      <div class="actions">
        <%= f.submit %>

        <%= button_to 'Create text',
        :controller => "texts",
        :action => "create",
        :method => :post,
        params: { page: "page" } %>
      </div>
    <% end %>
  </div>
</div>

app/views/texts/_showtext.html.erb
<p><%= truncate text.content, length: 50 %></p>
<div class="actions">
  <%= link_to 'Show', text %>
  <%= link_to 'Edit', edit_text_path(text) %>
  <%= link_to 'X', text, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/texts/_text.html.erb
<div class="text">
  <p class="left"><%= element.content %></p>
</div>

app/views/texts/create.js.erb
$(function () {
  $('#add_text').append( '<%= j render( "pages/showtext", :locals => { text: @text, page: @page }  ) %>' );
});

app/views/texts/destroy.js.erb
$('#text<%= @text.id %>').remove()

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form' %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Texts</h1>

<div class="sortable_texts" id="sortable_texts">

  <% @texts.each do |text| %>

      <%= render( "texts/showtext", text: text ) %>

  <% end %>

</div>

<div class="add_text">
  <div class="round5 grlinks" id="add_text" data-text="<%= @text %>">

    <p><%= link_to '+', new_text_path, remote: true, class: "round5" %></p>

  </div>
</div>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form' %>

<%= link_to 'Back', texts_path %>

app/views/texts/new.js.erb
$(function () {
  $('#add_widget').append( '<%= j render partial: "pages/newtextform", :locals => { text: @text, page: params[:page] } %>' );
});

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>
<p>Hey</p>
<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>